### ISSUE TITLE
Expiry and Valid From dates are incorrect

### ISSUE THREAD

**Issue by TheGuardianWolf** [JedS6391/NzCovidPass#11]
The validity and expiry dates on the Token object do not match up with the displayed dates on the COVID pass.

I have tried to shift them from UTC to NZT but this also does not work, it seems they are just a date rather than datetime.

Does the MoH give these date values as unix time? If so, can the time also be preserved?

```csharp
var validFrom = result.Token.ValidFrom;
var validTo = result.Token.ValidTo;
```

![image](https://user-images.githubusercontent.com/8168401/143796423-930f8486-a451-4f0a-aa44-29e10578e693.png)

In this image, these are the times in the token, but they are back by one day.

**Comment by JedS6391** [comment]
Thanks for reporting this issue. 

There were two problems here:

  * The time component was incorrectly being removed when converting between `DateTimeOffset` and `DateTime` for the `ValidTo`/`ValidFrom` properties.
  * The `DateTimeKind` wasn't being preserved which complicated conversion between time zones.

These problems are resolved in the [0.5.1 release](https://www.nuget.org/packages/NzCovidPass.Core/0.5.1).

You can use either of the following approaches to convert the UTC times represented by the token to a given timezone:

```cs
// Convert to local time zone
DateTime validToLocal = result.Token.ValidTo.ToLocalTime();
DateTimeOffset expiryLocal = result.Token.Expiry.ToLocalTime();

Debug.Assert(validToLocal == expiryLocal);

// Or converting to a specific time zone
TimeZoneInfo timeZone = TimeZoneInfo.FindSystemTimeZoneById("New Zealand Standard Time");

DateTime validToSpecificTimeZone = TimeZoneInfo.ConvertTimeFromUtc(result.Token.ValidTo, timeZone);
DateTimeOffset expirySpecificTimeZone = TimeZoneInfo.ConvertTime(result.Token.Expiry, timeZone);

Debug.Assert(validToSpecificTimeZone == expirySpecificTimeZone);
```

Please let me know if this works for you.

Cheers

**Comment by TheGuardianWolf** [comment]
Thanks for that quick update, this now gives the correct result in my application. Both dates reporting as the 20th after conversion, instead of the incorrect date of 19th.

For reference, I used the ConvertTimeFromUtc approach, and still using `Token.ValidFrom` and `Token.ValidTo`.

**Comment by TheGuardianWolf** [comment]
Just wanted to say this is working excellently after deployment and use, I am making a privacy focused verification tool, if you'd like to see your work in action :)

https://github.com/TheGuardianWolf/NzCovidPassTelegramBot

Also let me know if you'd need some help, always up to contributing upstream, but my understanding of the whole token specifics might be a bit lacking.

**Comment by JedS6391** [comment]
Really nice project! Always happy for contributions to be made :)
